# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def rx
  pod 'RxSwift'
  pod 'RxCocoa'
  #pod 'RxRealm'
  pod 'RxDataSources'
  pod 'Action'
  pod 'RxSwiftExt'
  pod 'RxOptional'
end

def networking
  pod 'Kingfisher'
  pod 'Moya/RxSwift', '~> 13.0.0'
end

def testing
  pod 'Quick'
  pod 'Nimble'
  pod 'Nimble-Snapshots'
  pod 'RxBlocking'
  pod 'RxTest'
end

def ui
  #pod "StatefulViewController", "~> 3.0"
  #pod 'SkeletonView'
  pod 'Reusable'
  pod 'YouTubePlayer'
end

target 'KarrosTech' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for KarrosTech
  rx()
  networking()
  #testing()
  ui()
end

target 'KarrosTechTests' do
  inherit! :search_paths
  # Pods for testing
  testing()
end
