# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRealm'
  pod 'RxDataSources'
  pod 'Action'
  pod 'RxSwiftExt'
  pod 'RxOptional'
end

def networking
  pod 'Kingfisher'
  pod 'Moya/RxSwift', '~> 14.0'
end

def testing
  pod 'Quick'
  pod 'Nimble'
  pod 'Nimble-Snapshots'
  pod 'RxBlocking'
  pod 'RxTest'
end

def ui
  pod "StatefulViewController", "~> 3.0"
  pod 'SkeletonView'
end

target 'KarrosTech' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  post_install do |installer|
   installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
   end
  end
  
  # Pods for KarrosTech
  rx()
  networking()
  testing()

end
